//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\NXOPEN\USER\Application\move.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: xian7
//              Version: NX 2306
//              Date: 07-14-2026  (Format: mm-dd-yyyy)
//              Time: 15:54 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "move.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;
using namespace NXOpen::Features;
using namespace NXOpen::GeometricUtilities;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(moveDlg::theSession) = NULL;
UI *(moveDlg::theUI) = NULL;

//------------------------------------------------------------------------------
// Forward declarations for helper functions defined at file scope
//------------------------------------------------------------------------------
static tag_t GetFirstSelectedTag(NXOpen::BlockStyler::BlockDialog* dialog, const char* blockId);
static tag_t GetBodyFromSelection(tag_t objTag);
static int GetBodyGlobalBBox(tag_t bodyTag, double minPt[3], double maxPt[3])
{
    if (bodyTag == NULL_TAG) return 1;
    NXOpen::Body* body = dynamic_cast<NXOpen::Body*>(NXOpen::NXObjectManager::Get(bodyTag));
    if (!body) return 1;
    std::vector<NXOpen::Edge*> edges = body->GetEdges();
    if (edges.empty()) return 1;
    minPt[0] = minPt[1] = minPt[2] = 1e308;
    maxPt[0] = maxPt[1] = maxPt[2] = -1e308;
    bool hasPt = false;
    for (NXOpen::Edge* edge : edges) {
        if (!edge) continue;
        NXOpen::Point3d v1, v2; edge->GetVertices(&v1, &v2); NXOpen::Point3d vlist[] = {v1, v2};
        for (const NXOpen::Point3d& v : vlist) {
            hasPt = true;
            if (v.X < minPt[0]) minPt[0] = v.X;
            if (v.Y < minPt[1]) minPt[1] = v.Y;
            if (v.Z < minPt[2]) minPt[2] = v.Z;
            if (v.X > maxPt[0]) maxPt[0] = v.X;
            if (v.Y > maxPt[1]) maxPt[1] = v.Y;
            if (v.Z > maxPt[2]) maxPt[2] = v.Z;
        }
    }
    if (!hasPt) return 1;
    return 0;
}

//==============================================================================
// Helper: ??enum?????tag??point01???
//==============================================================================
// Helper: safely read enum value (from dotAction.cpp pattern)
static int GetEnumValue(NXOpen::BlockStyler::Enumeration* enumBlock)
{
    if (enumBlock == NULL) return 0;
    try { PropertyList* p = enumBlock->GetProperties(); if (p) { int v = p->GetEnum("Value"); delete p; return v; } } catch(...) {}
    return 0;
}

// Helper: get first selected object tag
static tag_t GetFirstSelectedTag(NXOpen::BlockStyler::BlockDialog* dialog, const char* blockId)
{
    if (dialog == NULL) return NULL_TAG;
    try {
        PropertyList *selProps = dialog->GetBlockProperties(blockId);
        if (selProps) {
            std::vector<NXOpen::TaggedObject*> objs = selProps->GetTaggedObjectVector("SelectedObjects");
            delete selProps;
            if (!objs.empty() && objs[0] != NULL) return objs[0]->Tag();
        }
    } catch(...) {}
    return NULL_TAG;
}

// Helper: perform move or copy
static bool MoveOrCopyObject(tag_t objTag, const NXOpen::Point3d& srcPt, const NXOpen::Point3d& dstPt, bool copyMode)
{
    if (objTag == NULL_TAG) return false;
    double dx = dstPt.X - srcPt.X, dy = dstPt.Y - srcPt.Y, dz = dstPt.Z - srcPt.Z;
    if (fabs(dx)<1e-6 && fabs(dy)<1e-6 && fabs(dz)<1e-6) return true;
    NXOpen::Part *workPart = moveDlg::theSession->Parts()->Work();
    NXOpen::Features::MoveObjectBuilder *mb = workPart->BaseFeatures()->CreateMoveObjectBuilder(static_cast<NXOpen::Features::MoveObject*>(NULL));
    if (mb == NULL) return false;
    NXOpen::NXObject *nxObj = dynamic_cast<NXOpen::NXObject*>(NXOpen::NXObjectManager::Get(objTag));
    if (nxObj != NULL) {
        try { NXOpen::Features::RemoveParametersBuilder* rp = workPart->Features()->CreateRemoveParametersBuilder(); if (rp) { rp->Objects()->Add(nxObj); rp->Commit(); rp->Destroy(); } } catch(...) {}
        mb->ObjectToMoveObject()->Add(nxObj);
    } else { mb->Destroy(); return false; }
    NXOpen::GeometricUtilities::ModlMotion *m = mb->TransformMotion();
    m->SetOption(NXOpen::GeometricUtilities::ModlMotion::OptionsDeltaXyz);
    m->SetDeltaEnum(NXOpen::GeometricUtilities::ModlMotion::DeltaReferenceWcsWorkPart);
    m->DeltaXc()->SetNumberValue(dx);
    m->DeltaYc()->SetNumberValue(dy);
    m->DeltaZc()->SetNumberValue(dz);
    mb->SetMoveObjectResult(copyMode ? NXOpen::Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal : NXOpen::Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal);
    mb->Commit();
    mb->Destroy();
    return true;
}
static tag_t GetBodyFromSelection(tag_t objTag)
{
    if (objTag == NULL_TAG) return NULL_TAG;
    NXOpen::Body* body = dynamic_cast<NXOpen::Body*>(NXOpen::NXObjectManager::Get(objTag));
    if (body) return body->Tag();
    NXOpen::Face* face = dynamic_cast<NXOpen::Face*>(NXOpen::NXObjectManager::Get(objTag));
    if (face) {
        body = face->GetBody();
        if (body) return body->Tag();
    }
    return NULL_TAG;
}

static bool CalculateEnumPoint(tag_t objTag, int enumVal, bool isDest, double pt[3])
{
    pt[0]=pt[1]=pt[2]=0.0;
    if (isDest) {
        // For XO/ZO/YO/ABS/WCS we may need the body's bounding box
        switch (enumVal) {
            case 0: return true; // ABSåŽŸç‚¹ -> (0,0,0)
            case 3: { // WCSåŽŸç‚¹ via NXOpen
                NXOpen::Point3d wcsO = moveDlg::theSession->Parts()->Work()->WCS()->Origin();
                pt[0]=wcsO.X; pt[1]=wcsO.Y; pt[2]=wcsO.Z; return true;
            }
            case 2: case 4: case 6: { // ZOç‚?XOç‚?YOç‚?- use body bbox axis center
                tag_t bodyTag = GetBodyFromSelection(objTag);
                if (bodyTag == NULL_TAG) return false;
                double minPt[3], maxPt[3];
                if (GetBodyGlobalBBox(bodyTag, minPt, maxPt) != 0) return false;
                double cx=(minPt[0]+maxPt[0])/2.0, cy=(minPt[1]+maxPt[1])/2.0, cz=(minPt[2]+maxPt[2])/2.0;
                if (enumVal == 4) { pt[0]=cx; } // XOç‚?-> (cx,0,0)
                else if (enumVal == 6) { pt[1]=cy; } // YOç‚?-> (0,cy,0)
                else { pt[2]=cz; } // ZOç‚?-> (0,0,cz)
                return true;
            }
            case 5: case 1: break; // ä½“ä¸­å¿?é¢ä¸­å¿?-> fall through
            default: return false;
        }
    }
    tag_t bodyTag = GetBodyFromSelection(objTag);
    if (bodyTag == NULL_TAG) return false;
    double minPt[3], maxPt[3];
    if (GetBodyGlobalBBox(bodyTag, minPt, maxPt) != 0) return false;
    double cx=(minPt[0]+maxPt[0])/2.0, cy=(minPt[1]+maxPt[1])/2.0, cz;
    if (isDest) { if (enumVal==5) enumVal=1; else if (enumVal==1) enumVal=3; else enumVal=1; }
    switch (enumVal) {
        case 0: cz=maxPt[2]; break;
        case 1: cz=(minPt[2]+maxPt[2])/2.0; break;
        case 2: cz=minPt[2]; break;
        case 3: {
            NXOpen::Body* b = dynamic_cast<NXOpen::Body*>(NXOpen::NXObjectManager::Get(bodyTag));
            double fc[3]={0,0,0}; int fcnt=0;
            if (b) {
                for (NXOpen::Face* f : b->GetFaces()) {
                    if (!f) continue;
                    double fx=0,fy=0,fz=0; int e=0;
                    for (NXOpen::Edge* ed : f->GetEdges()) {
                        if (!ed) continue;
                        NXOpen::Point3d ev1, ev2; ed->GetVertices(&ev1, &ev2); fx+=ev1.X+ev2.X;fy+=ev1.Y+ev2.Y;fz+=ev1.Z+ev2.Z;e+=2;
                    }
                    if (e>0) { fc[0]+=fx/e;fc[1]+=fy/e;fc[2]+=fz/e;fcnt++; }
                }
            }
            if (fcnt>0) { pt[0]=fc[0]/fcnt;pt[1]=fc[1]/fcnt;pt[2]=fc[2]/fcnt;return true; }
            cz=(minPt[2]+maxPt[2])/2.0; break;
        }
        default: cz=(minPt[2]+maxPt[2])/2.0; break;
    }
    pt[0]=cx;pt[1]=cy;pt[2]=cz;
    return true;
}

moveDlg()
{
    try
    {
        // Initialize the NX Open C++ API environment
        moveDlg::theSession = NXOpen::Session::GetSession();
        moveDlg::theUI = UI::GetUI();
        theDlxFileName = "move.dlx";
        theDialog = moveDlg::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &moveDlg::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &moveDlg::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &moveDlg::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &moveDlg::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &moveDlg::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
~moveDlg()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    moveDlg *themoveDlg = NULL;
    try
    {
        themoveDlg = new moveDlg();
        // The following method shows the dialog immediately
        themoveDlg->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        moveDlg::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(themoveDlg != NULL)
    {
        delete themoveDlg;
        themoveDlg = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        moveDlg::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse moveDlg::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        moveDlg::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void moveDlg::initialize_cb()
{
    try
    {
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point01"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
        point0SetByUser = false;
        point01SetByUser = false;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        moveDlg::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void moveDlg::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        moveDlg::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int moveDlg::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        moveDlg::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int moveDlg::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    int errorCode = 0;
    try
    {
        if(block == button0) {
            tag_t objTag = GetFirstSelectedTag(theDialog,"selection0");
            if (objTag == NULL_TAG) { theUI->NXMessageBox()->Show("moveDlg",NXOpen::NXMessageBox::DialogTypeError,"No object selected"); return 0; }
            NXOpen::Point3d srcPt(0,0,0), dstPt(0,0,0);
            if (point0SetByUser) { try { srcPt = point0->Point(); } catch(...) {} }
            else { double p[3]; if (CalculateEnumPoint(objTag, GetEnumValue(enum0), false, p)) srcPt = Point3d(p[0],p[1],p[2]); }
            if (point01SetByUser) { try { dstPt = point01->Point(); } catch(...) {} }
            else { double p[3]; if (CalculateEnumPoint(objTag, GetEnumValue(enum01), true, p)) dstPt = Point3d(p[0],p[1],p[2]); }
            if (MoveOrCopyObject(objTag, srcPt, dstPt, false))
                theUI->NXMessageBox()->Show("moveDlg",NXOpen::NXMessageBox::DialogTypeInformation,"Completed");
            else
                theUI->NXMessageBox()->Show("moveDlg",NXOpen::NXMessageBox::DialogTypeError,"Failed");
        }
        else if(block == button01) {
            tag_t objTag = GetFirstSelectedTag(theDialog,"selection0");
            if (objTag == NULL_TAG) { theUI->NXMessageBox()->Show("moveDlg",NXOpen::NXMessageBox::DialogTypeError,"No object selected"); return 0; }
            NXOpen::Point3d srcPt(0,0,0), dstPt(0,0,0);
            if (point0SetByUser) { try { srcPt = point0->Point(); } catch(...) {} }
            else { double p[3]; if (CalculateEnumPoint(objTag, GetEnumValue(enum0), false, p)) srcPt = Point3d(p[0],p[1],p[2]); }
            if (point01SetByUser) { try { dstPt = point01->Point(); } catch(...) {} }
            else { double p[3]; if (CalculateEnumPoint(objTag, GetEnumValue(enum01), true, p)) dstPt = Point3d(p[0],p[1],p[2]); }
            if (MoveOrCopyObject(objTag, srcPt, dstPt, true))
                theUI->NXMessageBox()->Show("moveDlg",NXOpen::NXMessageBox::DialogTypeInformation,"Completed");
            else
                theUI->NXMessageBox()->Show("moveDlg",NXOpen::NXMessageBox::DialogTypeError,"Failed");
        }
        else if(block == selection0) {}
        else if(block == point0) { point0SetByUser = true; }
        else if(block == enum0) {}
        else if(block == point01) { point01SetByUser = true; }
        else if(block == enum01) {}
    }
    catch(std::exception& ex) {
        moveDlg::theUI->NXMessageBox()->Show("Block Styler",NXOpen::NXMessageBox::DialogTypeError,ex.what());
        errorCode = 1;
    }
    return errorCode;
}
int moveDlg::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        moveDlg::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* moveDlg::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

//==============================================================================
// Helper function: Get the first selected object tag from a Selection block
//==============================================================================


