//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\NX\Applocation\MoveandCut.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 15378
//              Version: NX 2306
//              Date: 07-15-2026  (Format: mm-dd-yyyy)
//              Time: 09:44 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "MoveandCut.hpp"
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <string.h>
#undef CreateDialog
EXTERN_C IMAGE_DOS_HEADER __ImageBase;
static char g_dlxPath[260];
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(MoveandCut::theSession) = NULL;
UI *(MoveandCut::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
MoveandCut::MoveandCut()
{
    try
    {
        // Initialize the NX Open C++ API environment
        MoveandCut::theSession = NXOpen::Session::GetSession();
        MoveandCut::theUI = UI::GetUI();
        theDlxFileName = "MoveandCut.dlx";
        HMODULE hMod = (HMODULE)&__ImageBase;
        GetModuleFileNameA(hMod, g_dlxPath, 260);
        int ln = strlen(g_dlxPath); g_dlxPath[ln-3]='d'; g_dlxPath[ln-2]='l'; g_dlxPath[ln-1]='x';
        theDlxFileName = g_dlxPath;
        m_MoveMode = 0;
        theDialog = MoveandCut::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &MoveandCut::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &MoveandCut::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &MoveandCut::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &MoveandCut::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &MoveandCut::dialogShown_cb));
        theDialog->AddEnableOKButtonHandler(make_callback(this, &MoveandCut::enableOKButton_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
MoveandCut::~MoveandCut()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    MoveandCut *theMoveandCut = NULL;
    try
    {
        theMoveandCut = new MoveandCut();
        // The following method shows the dialog immediately
        theMoveandCut->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MoveandCut::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theMoveandCut != NULL)
    {
        delete theMoveandCut;
        theMoveandCut = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MoveandCut::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse MoveandCut::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MoveandCut::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void MoveandCut::initialize_cb()
{
    try
    {
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point01"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MoveandCut::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void MoveandCut::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MoveandCut::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------



// Helper: get body bounding box [xmin, ymin, zmin, xmax, ymax, zmax]
static bool getBodyBBox(NXOpen::BlockStyler::SelectObject* sel, double box[6])
{
    if (sel == NULL) return false;
    std::vector<NXOpen::TaggedObject*> objects = sel->GetSelectedObjects();
    if (objects.size() == 0) return false;
    NXOpen::Body* b = dynamic_cast<NXOpen::Body*>(objects[0]);
    if (b == NULL) return false;
    try
    {
        std::vector<NXOpen::NXObject*> objList;
        objList.push_back(dynamic_cast<NXOpen::NXObject*>(b));
        std::vector<NXOpen::Point3d> pts, dirs;
        std::vector<double> lengths;
        NXOpen::Point3d origin, extreme;
        MoveandCut::theSession->Measurement()->GetBoundingBoxProperties(
            objList, 0, NXOpen::Point3d(0,0,0), false, pts, dirs, lengths, &origin, &extreme, NULL);
        if (pts.size() >= 8)
        {
            double xmin=pts[0].X,ymin=pts[0].Y,zmin=pts[0].Z,xmax=pts[0].X,ymax=pts[0].Y,zmax=pts[0].Z;
            for (int i=1;i<8;i++) {
                if (pts[i].X<xmin)xmin=pts[i].X; if (pts[i].Y<ymin)ymin=pts[i].Y; if (pts[i].Z<zmin)zmin=pts[i].Z;
                if (pts[i].X>xmax)xmax=pts[i].X; if (pts[i].Y>ymax)ymax=pts[i].Y; if (pts[i].Z>zmax)zmax=pts[i].Z;
            }
            box[0]=xmin;box[1]=ymin;box[2]=zmin;box[3]=xmax;box[4]=ymax;box[5]=zmax;
            return true;
        }
    }
    catch(...) {}
    return false;
}

// Helper: read Enumeration value using correct API (ValueAsString + GetEnumMembers)
static int readEnumIndex(NXOpen::BlockStyler::Enumeration* e, int defaultVal)
{
    if (e == NULL) return defaultVal;
    try
    {
        std::vector<NXString> members = e->GetEnumMembers();
        NXString current = e->ValueAsString();
        for (int i = 0; i < (int)members.size(); i++)
        {
            if (strcmp(members[i].GetText(), current.GetText()) == 0)
                return i;
        }
    }
    catch (...) { }
    return defaultVal;
}

int MoveandCut::apply_cb()
{
    int errorCode = 0;
    try
    {
        // 1. Validate selection
        if (selection0->GetSelectedObjects().size() == 0)
        {
            theUI->NXMessageBox()->Show("Error", NXOpen::NXMessageBox::DialogTypeWarning, "Select a body first");
            return 1;
        }

        // 2. Read start/end point modes
        double startPt[3] = {0, 0, 0};
        double endPt[3]   = {0, 0, 0};

        // Start point: manual point first, fall back to enum
        bool hasManualStart = false;
        try { NXOpen::Point3d pt = point0->Point(); if (pt.X != 0.0 || pt.Y != 0.0 || pt.Z != 0.0) { startPt[0]=pt.X; startPt[1]=pt.Y; startPt[2]=pt.Z; hasManualStart=true; } } catch(...) {}

        if (!hasManualStart)
        {
            int sMode = readEnumIndex(enum0, 1);
            switch (sMode)
            {
            case 0: { double b[6]; if (getBodyBBox(selection0, b)) { startPt[0]=(b[0]+b[3])/2; startPt[1]=(b[1]+b[4])/2; startPt[2]=b[5]; } } break;
            case 1: { double b[6]; if (getBodyBBox(selection0, b)) { startPt[0]=(b[0]+b[3])/2; startPt[1]=(b[1]+b[4])/2; startPt[2]=(b[2]+b[5])/2; } } break;
            case 2: { double b[6]; if (getBodyBBox(selection0, b)) { startPt[0]=(b[0]+b[3])/2; startPt[1]=(b[1]+b[4])/2; startPt[2]=b[2]; } } break;
            case 3: { try { NXOpen::Point3d pt = point0->Point(); startPt[0]=pt.X; startPt[1]=pt.Y; startPt[2]=pt.Z; } catch(...) {} } break;
            }
        }

        // End point: manual point first, fall back to enum
        bool hasManualEnd = false;
        try { NXOpen::Point3d pt = point01->Point(); if (pt.X != 0.0 || pt.Y != 0.0 || pt.Z != 0.0) { endPt[0]=pt.X; endPt[1]=pt.Y; endPt[2]=pt.Z; hasManualEnd=true; } } catch(...) {}

        if (!hasManualEnd)
        {
            int eMode = readEnumIndex(enum01, 3);
            switch (eMode)
            {
            case 0: endPt[0]=0; endPt[1]=0; endPt[2]=0; break;
            case 1: { try { NXOpen::Point3d pt = point01->Point(); endPt[0]=pt.X; endPt[1]=pt.Y; endPt[2]=pt.Z; } catch(...) {} } break;
            case 2: { double b[6]; if (getBodyBBox(selection0, b)) { endPt[0]=(b[0]+b[3])/2; endPt[1]=(b[1]+b[4])/2; endPt[2]=b[2]; } } break;
            case 3: { NXOpen::Point3d wcsOrigin = theSession->Parts()->Work()->WCS()->Origin(); endPt[0]=wcsOrigin.X; endPt[1]=wcsOrigin.Y; endPt[2]=wcsOrigin.Z; } break;
            case 4: { double b[6]; if (getBodyBBox(selection0, b)) { endPt[0]=b[0]; endPt[1]=(b[1]+b[4])/2; endPt[2]=(b[2]+b[5])/2; } } break;
            case 5: { double b[6]; if (getBodyBBox(selection0, b)) { endPt[0]=(b[0]+b[3])/2; endPt[1]=(b[1]+b[4])/2; endPt[2]=(b[2]+b[5])/2; } } break;
            case 6: { double b[6]; if (getBodyBBox(selection0, b)) { endPt[0]=(b[0]+b[3])/2; endPt[1]=b[1]; endPt[2]=(b[2]+b[5])/2; } } break;
            }
        }

        // 3. Compute delta
        double delta[3];
        delta[0] = endPt[0] - startPt[0];
        delta[1] = endPt[1] - startPt[1];
        delta[2] = endPt[2] - startPt[2];

        // 4. Create MoveObjectBuilder
        Part* wp = theSession->Parts()->Work();
        Features::MoveObjectBuilder* builder = wp->BaseFeatures()->CreateMoveObjectBuilder(NULL);

        std::vector<NXOpen::NXObject*> objs;
        std::vector<NXOpen::TaggedObject*> selList = selection0->GetSelectedObjects();
        if (selList.size() > 0) objs.push_back(dynamic_cast<NXOpen::NXObject*>(selList[0]));
        builder->ObjectToMoveObject()->SetArray(objs);

        builder->SetMoveParents(false);

        GeometricUtilities::ModlMotion* motion = builder->TransformMotion();
        motion->SetOption(GeometricUtilities::ModlMotion::OptionsDeltaXyz);
        motion->SetDeltaX(delta[0]);
        motion->SetDeltaY(delta[1]);
        motion->SetDeltaZ(delta[2]);

        // Move mode: associative feature. Copy mode: simple copy.
        if (m_MoveMode == 0)
        {
            builder->SetAssociative(true);
            builder->SetMoveParents(false);
            builder->SetMoveObjectResult(Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal);
        }
        else
        {
            builder->SetMoveObjectResult(Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal);
        }

        // 5. Commit and update
        builder->Commit();

        NXOpen::Session::UndoMarkId mark = theSession->SetUndoMark(NXOpen::Session::MarkVisibilityVisible, "MoveandCut");
        theSession->UpdateManager()->DoUpdate(mark);
        builder->Destroy();

        char msg[256];
        if (m_MoveMode == 0)
            sprintf(msg, "Move OK. Delta: X=%.1f Y=%.1f Z=%.1f", delta[0], delta[1], delta[2]);
        else
            sprintf(msg, "Copy OK. Delta: X=%.1f Y=%.1f Z=%.1f", delta[0], delta[1], delta[2]);
        theUI->NXMessageBox()->Show("Result", NXOpen::NXMessageBox::DialogTypeInformation, msg);
    }
    catch(exception& ex)
    {
        errorCode = 1;
        theUI->NXMessageBox()->Show("Error", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int MoveandCut::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == button0)
        {
            m_MoveMode = 0;
        }
        else if(block == button01)
        {
            m_MoveMode = 1;
        }
        else if(block == selection0)
        {
        //---------Enter your code here-----------
        }
        else if(block == point0)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
        else if(block == point01)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum01)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MoveandCut::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int MoveandCut::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        MoveandCut::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
bool MoveandCut::enableOKButton_cb() { return true; }

PropertyList* MoveandCut::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}





